version: '3.4'

services:

  experiment:
    build:
      context: services/experiment
    environment:
      - DB_MLFLOW_PASS=${DB_MLFLOW_PASS}
      - DB_OPTUNA_PASS=${DB_OPTUNA_PASS}
      - S3_BUCKET=${S3_BUCKET}
      - S3_AUTH_KEY_ID=${S3_AUTH_KEY_ID}
      - S3_AUTH_SECRET_KEY=${S3_AUTH_SECRET_KEY}
    networks:
      - ax-ml-ops_ax

networks:
  ax-ml-ops_ax:
    external: true
      