#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DB_OPTUNA_USER} WITH PASSWORD '${DB_OPTUNA_PASS}';
	CREATE DATABASE ${DB_OPTUNA_NAME};
	ALTER DATABASE ${DB_OPTUNA_NAME} OWNER TO ${DB_OPTUNA_USER};
	GRANT ALL ON SCHEMA public TO ${DB_OPTUNA_USER};
EOSQL