#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DB_AIRFLOW_USER} WITH PASSWORD '${DB_AIRFLOW_PASS}';
	CREATE DATABASE ${DB_AIRFLOW_NAME};
	ALTER DATABASE ${DB_AIRFLOW_NAME} OWNER TO ${DB_AIRFLOW_USER};
	GRANT ALL ON SCHEMA public TO ${DB_AIRFLOW_USER};
EOSQL