#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER mlops WITH PASSWORD '${DB_MLOPS_PASS}';
	CREATE DATABASE mlops;
	GRANT ALL ON SCHEMA public TO mlops;
	GRANT ALL PRIVILEGES ON DATABASE mlops TO mlops;
	ALTER DATABASE mlops OWNER TO mlops;

	CREATE USER optuna WITH PASSWORD '${DB_OPTUNA_PASS}';
	CREATE DATABASE optuna;
	GRANT ALL ON SCHEMA public TO optuna;
	GRANT ALL PRIVILEGES ON DATABASE optuna TO optuna;
	ALTER DATABASE optuna OWNER TO optuna;
EOSQL