#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DB_MLFLOW_USER} WITH PASSWORD '${DB_MLFLOW_PASS}';
	CREATE DATABASE ${DB_MLFLOW_NAME};
	ALTER DATABASE ${DB_MLFLOW_NAME} OWNER TO ${DB_MLFLOW_USER};
	GRANT ALL ON SCHEMA public TO ${DB_MLFLOW_USER};
EOSQL